### ISSUE TITLE
When switching between projects, hitting save can delete a project's data unintentionally

### ISSUE THREAD

**Issue by sibnerian** [patrickhulce/codereview#3]
Enter some data for, say, hw03. Then switch to a new project, then type hw03 in the search bar. QUICKLY hit save, then load. hw03 will be overwritten by the new project, which has no data!

**Comment by patrickhulce** [comment]
From the way you've described it, that sounds like the intended behavior. Entering the name of a new project without hitting 'Load' and then hitting 'Save', should overwrite that project. The intended process is 
1. Enter the name of a project.
2. Hit load to bring up that project.

**Comment by sibnerian** [comment]
So basically, you can override a project by clicking the wrong button... I think the dirty fix here is to add a confirm dialog. Then maybe in the future, a 'create project'  button that controls the active project, instead of just the input's value.

**Comment by patrickhulce** [comment]
Right, good point. The whole project system is a prime candidate for
overhaul already, but I'll try to add a confirm dialog for now.
